service: yoongi

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev

functions:
  csrf_function:
    handler: dist/handler.myHandler
    events:
      - http:
          path: path_csrf
          method: post
          cors: true

